### ISSUE TITLE
Dev installation for python 3.11 is broken

### ISSUE THREAD

**Issue by dangunter** [watertap-org/watertap-ui#105]
## Summary 
FastAPI and pyinstaller versions need to be relaxed in `backend/requirements-dev.txt` (for Python 3.11) and instructions for actually installing the backend Python code should be in the README.

## Steps to reproduce (inside prommis installation, where I'm using it)

1. Clone and install prommis
```
git clone https://github.com/dangunter/prommis.git
cd prommis
conda create -n prommis-test1 python=3.11 -y
conda activate prommis-test1
pip install -r requirements-dev.txt
```
2. Inside Prommis, clone and install watertap-ui
```
git clone https://github.com/watertap-org/watertap-ui.git
cd .\watertap-ui\backend\
pip install -r .\requirements-dev.txt
```
last command gives this error at the end:
```
ERROR: Ignored the following versions that require a different python version: 4.10 Requires-Python <3.11,>=3.6; 4.6 Requires-Python <3.11,>=3.6; 4.7 Requires-Python <3.11,>=3.6; 4.8 Requires-Python <3.11,>=3.6; 4.9 Requires-Python <3.11,>=3.6; 5.0 Requires-Python <3.11,>=3.7; 5.0.1 Requires-Python <3.11,>=3.7; 5.1 Requires-Python <3.11,>=3.7; 5.2 Requires-Python <3.11,>=3.7; 5.3 Requires-Python <3.11,>=3.7; 5.4 Requires-Python <3.11,>=3.7; 5.4.1 Requires-Python <3.11,>=3.7
ERROR: Could not find a version that satisfies the requirement pyinstaller==5.3 (from versions: 2.0, 2.1, 3.0, 3.1, 3.1.1, 3.2, 3.2.1, 3.3, 3.3.1, 3.4, 3.5, 3.6, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.5.1, 5.5, 5.6, 5.6.1, 5.6.2, 5.7.0, 5.8.0, 5.9.0, 5.10.0, 5.10.1, 5.11.0, 5.12.0, 5.13.0, 5.13.1, 5.13.2, 6.0.0, 6.1.0, 6.2.0, 6.3.0)
ERROR: No matching distribution found for pyinstaller==5.3
```
So, remove fixed version for pyinstaller and try again.
```
cp requirements-dev.txt requirements-new.txt
# edit to remove '== 5.3' at end of pyinstaller line
pip install -r .\requirements-new.txt
```
This also gives some error about Sqlalchemy but more importantly fastapi is borked
```
❯ python -c "import fastapi"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\dkgun\miniconda3\envs\prommis-test1\Lib\site-packages\fastapi\__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "C:\Users\dkgun\miniconda3\envs\prommis-test1\Lib\site-packages\fastapi\applications.py", line 15, in <module>
    from fastapi import routing
  File "C:\Users\dkgun\miniconda3\envs\prommis-test1\Lib\site-packages\fastapi\routing.py", line 23, in <module>
    from fastapi.dependencies.models import Dependant
  File "C:\Users\dkgun\miniconda3\envs\prommis-test1\Lib\site-packages\fastapi\dependencies\models.py", line 3, in <module>
    from fastapi.security.base import SecurityBase
  File "C:\Users\dkgun\miniconda3\envs\prommis-test1\Lib\site-packages\fastapi\security\__init__.py", line 1, in <module>
    from .api_key import APIKeyCookie as APIKeyCookie
  File "C:\Users\dkgun\miniconda3\envs\prommis-test1\Lib\site-packages\fastapi\security\api_key.py", line 3, in <module>
    from fastapi.openapi.models import APIKey, APIKeyIn
  File "C:\Users\dkgun\miniconda3\envs\prommis-test1\Lib\site-packages\fastapi\openapi\models.py", line 103, in <module>
    class Schema(BaseModel):
  File "C:\Users\dkgun\miniconda3\envs\prommis-test1\Lib\site-packages\pydantic\main.py", line 292, in __new__
    cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dkgun\miniconda3\envs\prommis-test1\Lib\site-packages\pydantic\utils.py", line 258, in generate_model_signature
    merged_params[param_name] = Parameter(
                                ^^^^^^^^^^
  File "C:\Users\dkgun\miniconda3\envs\prommis-test1\Lib\inspect.py", line 2725, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: 'not' is not a valid parameter name
````
In order to fix this, remove some fixed versions on fastapi and friends
```
# edit requirements-new.dev to have these 3 lines in place of what's there:
#  pydantic > 1.10.0, < 2.0.0
# pyinstaller
# pyinstaller-hooks-contrib
pip install -r requirements-new.txt
```
Now `python -c 'import fastapi'` runs without errors.

**Comment by lbianchi-lbl** [comment]
Can you post the output of `pip freeze` so that we can have a reference?
